-- 코드를 입력하세요
SELECT UGU.USER_ID,	UGU.NICKNAME, sum(USB.PRICE) as TOTAL_SALES
from USED_GOODS_BOARD USB, USED_GOODS_USER UGU
where USB.WRITER_ID = UGU.USER_ID
and STATUS = 'DONE'
group by UGU.USER_ID,UGU.NICKNAME
having sum(USB.PRICE) >= 700000
order by sum(USB.PRICE);