-- 코드를 입력하세요
SELECT A.AUTHOR_ID,	A.AUTHOR_NAME	,B.CATEGORY, sum(BS.SALES*B.PRICE) as TOTAL_SALES
from BOOK B,AUTHOR A,BOOK_SALES BS 
where B.AUTHOR_ID = A.AUTHOR_ID and B.BOOK_ID = BS.BOOK_ID 
and to_char(SALES_DATE,'YYYY-MM') = '2022-01'
group by A.AUTHOR_ID,	A.AUTHOR_NAME,B.CATEGORY
order by AUTHOR_ID asc , CATEGORY desc;