-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,
SUM(P.PRICE * S.SALES_AMOUNT) as SALES
from PRODUCT P, OFFLINE_SALE S
where P.PRODUCT_ID = S.PRODUCT_ID
group by P.PRODUCT_CODE
order by SALES desc, P.PRODUCT_CODE;